
import type { Loan, Rider, Payment, Bike, SavingInsight, Document } from "./types";
import { subDays, addDays, formatISO } from 'date-fns';

const today = new Date();

export const initialRiders: Rider[] = [
  {
    id: "rider-1",
    name: "Juma Hassan",
    phone: "0712345678",
    email: "juma.hassan@example.com",
    plateNumber: "T 123 BCD",
    vehicleType: "Boda Boda",
    chassisNumber: "MC-123456789-Z",
    engineNumber: "ENG-998877-X",
    shahidiNumber: "SH-9988", 
    dailyFee: 10000, 
    paymentFrequency: 'Daily', 
    contractStart: formatISO(subDays(today, 5)), 
    contractEnd: formatISO(addDays(today, 535)), 
    active: true, 
    bikeId: "bike-1", 
    createdAt: formatISO(subDays(today, 5)),
    location: { lat: -6.7924, lng: 39.2083 },
    guarantorName: "Hassan Omari",
    guarantorPhone: "0711000001",
    witnessName: "Bakari Ally",
    witnessPhone: "0711000002"
  },
  {
    id: "rider-2",
    name: "Ally Ramadhan",
    phone: "0788112233",
    email: "ally.ramadhan@example.com",
    plateNumber: "T 445 DEF",
    vehicleType: "Boda Boda",
    chassisNumber: "MC-445566778-Y",
    engineNumber: "ENG-112233-W",
    shahidiNumber: "SH-1122", 
    dailyFee: 10000, 
    paymentFrequency: 'Daily', 
    contractStart: formatISO(subDays(today, 10)), 
    contractEnd: formatISO(addDays(today, 530)), 
    active: true, 
    bikeId: "bike-2", 
    createdAt: formatISO(subDays(today, 10)),
    location: { lat: -6.8234, lng: 39.2694 },
    guarantorName: "Ramadhan Juma",
    guarantorPhone: "0788000001"
  },
  {
    id: "rider-3",
    name: "Sofia Said",
    phone: "0655443322",
    email: "sofia.said@example.com",
    plateNumber: "T 789 GHI",
    vehicleType: "Boda Boda",
    chassisNumber: "MC-789012345-V",
    engineNumber: "ENG-334455-S",
    shahidiNumber: "SH-4455", 
    dailyFee: 10000, 
    paymentFrequency: 'Daily', 
    contractStart: formatISO(subDays(today, 3)), 
    contractEnd: formatISO(addDays(today, 537)), 
    active: true, 
    bikeId: "bike-3", 
    createdAt: formatISO(subDays(today, 3)),
    location: { lat: -6.7724, lng: 39.2383 },
    guarantorName: "Said Ally",
    guarantorPhone: "0655000001"
  },
  {
    id: "rider-4",
    name: "Baraka Mwangi",
    phone: "0711998877",
    email: "baraka.mwangi@example.com",
    plateNumber: "T 119 HJL",
    vehicleType: "Boda Boda",
    chassisNumber: "MC-119228833-U",
    engineNumber: "ENG-776655-T",
    shahidiNumber: "SH-7766", 
    dailyFee: 10000, 
    paymentFrequency: 'Daily', 
    contractStart: formatISO(subDays(today, 7)), 
    contractEnd: formatISO(addDays(today, 533)), 
    active: true, 
    bikeId: "bike-4", 
    createdAt: formatISO(subDays(today, 7)),
    location: { lat: -6.8024, lng: 39.2183 },
    guarantorName: "Mwangi Karanja",
    guarantorPhone: "0711000004"
  },
  {
    id: "rider-5",
    name: "Amina Saleh",
    phone: "0622334455",
    email: "amina.saleh@example.com",
    plateNumber: "T 042 GFK",
    vehicleType: "Boda Boda",
    chassisNumber: "MC-042339944-R",
    engineNumber: "ENG-990011-Q",
    shahidiNumber: "SH-3344", 
    dailyFee: 10000, 
    paymentFrequency: 'Daily', 
    contractStart: formatISO(subDays(today, 2)), 
    contractEnd: formatISO(addDays(today, 538)), 
    active: true, 
    bikeId: "bike-5", 
    createdAt: formatISO(subDays(today, 2)),
    location: { lat: -6.8124, lng: 39.2483 },
    guarantorName: "Saleh Juma",
    guarantorPhone: "0622000001"
  }
];

export const initialBikes: Bike[] = [
  { id: "bike-1", plateNumber: "T 123 BCD", model: "Boxer 150", ownerId: "admin" },
  { id: "bike-2", plateNumber: "T 445 DEF", model: "TVS HLX", ownerId: "admin" },
  { id: "bike-3", plateNumber: "T 789 GHI", model: "Boxer 150", ownerId: "admin" },
  { id: "bike-4", plateNumber: "T 119 HJL", model: "TVS HLX", ownerId: "admin" },
  { id: "bike-5", plateNumber: "T 042 GFK", model: "Bajaj RE", ownerId: "admin" }
];

export const initialPayments: Payment[] = [
  { id: "p1", riderId: "rider-1", amount: 10000, selcomRef: "SC-P1", status: "verified", recordedAt: formatISO(subDays(today, 1)) },
  { id: "p2", riderId: "rider-2", amount: 10000, selcomRef: "SC-P2", status: "verified", recordedAt: formatISO(subDays(today, 1)) },
  { id: "p3", riderId: "rider-3", amount: 10000, selcomRef: "SC-P3", status: "verified", recordedAt: formatISO(today) },
];

export const initialLoans: Loan[] = [
  {
    id: "loan-1",
    clientId: "rider-1",
    loanType: "Boda Boda",
    principalAmount: 2500000,
    outstandingBalance: 2470000,
    interestRate: 0.15,
    loanTermMonths: 18,
    startDate: formatISO(subDays(today, 5)),
    endDate: formatISO(addDays(today, 535)),
    nextPaymentDueDate: formatISO(addDays(today, 1)),
    minimumPaymentAmount: 10000,
    totalAmountPaid: 30000,
    loanStatus: "Active",
    progressPercentage: 1.2,
  },
  {
    id: "loan-2",
    clientId: "rider-2",
    loanType: "Boda Boda",
    principalAmount: 2500000,
    outstandingBalance: 2450000,
    interestRate: 0.15,
    loanTermMonths: 18,
    startDate: formatISO(subDays(today, 10)),
    endDate: formatISO(addDays(today, 530)),
    nextPaymentDueDate: formatISO(addDays(today, 1)),
    minimumPaymentAmount: 10000,
    totalAmountPaid: 50000,
    loanStatus: "Active",
    progressPercentage: 2.0,
  },
  {
    id: "loan-3",
    clientId: "rider-3",
    loanType: "Boda Boda",
    principalAmount: 2500000,
    outstandingBalance: 2480000,
    interestRate: 0.15,
    loanTermMonths: 18,
    startDate: formatISO(subDays(today, 3)),
    endDate: formatISO(addDays(today, 537)),
    nextPaymentDueDate: formatISO(addDays(today, 1)),
    minimumPaymentAmount: 10000,
    totalAmountPaid: 20000,
    loanStatus: "Active",
    progressPercentage: 0.8,
  },
  {
    id: "loan-4",
    clientId: "rider-4",
    loanType: "Boda Boda",
    principalAmount: 2500000,
    outstandingBalance: 2490000,
    interestRate: 0.15,
    loanTermMonths: 18,
    startDate: formatISO(subDays(today, 7)),
    endDate: formatISO(addDays(today, 533)),
    nextPaymentDueDate: formatISO(addDays(today, 1)),
    minimumPaymentAmount: 10000,
    totalAmountPaid: 10000,
    loanStatus: "Active",
    progressPercentage: 0.4,
  },
  {
    id: "loan-5",
    clientId: "rider-5",
    loanType: "Boda Boda",
    principalAmount: 2500000,
    outstandingBalance: 2495000,
    interestRate: 0.15,
    loanTermMonths: 18,
    startDate: formatISO(subDays(today, 2)),
    endDate: formatISO(addDays(today, 538)),
    nextPaymentDueDate: formatISO(addDays(today, 1)),
    minimumPaymentAmount: 10000,
    totalAmountPaid: 5000,
    loanStatus: "Active",
    progressPercentage: 0.2,
  }
];

export const initialSavings: SavingInsight = {
  id: "save-1",
  mogoInterestRate: 0.15,
  competitorInterestRate: 0.22,
  monthlySavings: 35000,
  totalSavingsToDate: 140000,
};

export const initialDocuments: Document[] = [
  {
    id: "doc-1",
    clientId: "rider-1",
    documentType: "Logbook",
    documentName: "Vehicle Logbook - T 123 BCD",
    fileUrl: "#",
    uploadDate: formatISO(subDays(today, 5)),
  }
];
